name: Update Schedule

on:
  schedule:
    - cron: '*/30 * * * *' # Запускати кожні 15 хвилин
  workflow_dispatch:       # Кнопка "Запустити зараз"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install libs
        run: |
          python -m pip install --upgrade pip
          pip install requests pytz

      - name: Run parser
        run: python parser/parser.py

      - name: Commit results
        run: |
          git config --global user.name 'SvitloBot'
          git config --global user.email 'bot@svitlo.pro'
          git add schedule.json
          # Якщо файл змінився - комітимо і пушимо
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update schedule [skip ci]" && git push)